### ISSUE TITLE
Calling getOffers as non owner

### ISSUE THREAD

**Issue by ghost** [Floari33/CarTract#1]
Every time I call getOffers() as a non owner (thisMachine.besitzer != msg.sender) I receive following error message (in remix ide): 

**error: Failed to decode output: Error: overflow (operation="setValue", fault="overflow", details="Number can only safely store up to 53 bits", version=4.0.28)**

![image](https://user-images.githubusercontent.com/36666207/59049717-edea5d00-8888-11e9-8c7b-307ae5107540.png)

**Comment by Floari33** [comment]
Hello,

thank you for your interest. 
Our implementation for the error-handling has not finished yet. But as you can see in the code, it is a MUST to be the owner of the Machine to call this function. Otherwise there wouldn't exist an economic competition between the interested potential buyer, what would be a disadvantage for the seller.
